apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  namespace: codetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: codecalm/codetest-upload:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: RUN_MEMORY
              value: "256m"
            - name: RUN_CPUS
              value: "0.5"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: codetest
spec:
  selector:
    app: upload
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: upload-hpa
  namespace: codetest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upload
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
